command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: "AGENT_ENDPOINT_NAME"
    value: "agents_bo_cheng_dnb_demos-agents-managed-mcp-model"